name: Continuous master build

on:
  push:
    branches:
      - master

jobs:
  clippy:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: target/
          key: cargo-clippy-cache-${{ matrix.arch.target }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-01-08
          override: true
          components: clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy

  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    strategy:
      matrix:
        arch:
          - { name: 'x86_64', os: 'ubuntu-20.04', target: 'x86_64-unknown-linux-gnu', cross: false }
    runs-on: ${{ matrix.arch.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            target/
          key: cargo-build-cache-${{ matrix.arch.target }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-01-08
          override: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features --target=${{ matrix.arch.target }}
          use-cross: ${{ matrix.arch.cross }}
        env:
          JQ_LIB_DIR: /usr/lib/x86_64-linux-gnu
      - name: Rename artifact
        run: |
          mv target/${{ matrix.arch.target }}/release/deckshot target/${{ matrix.arch.target }}/release/deckshot-tip-${{ matrix.arch.name }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: deckshot-tip-${{ matrix.arch.name }}
          path: |
            target/${{ matrix.arch.target }}/release/deckshot-tip-${{ matrix.arch.name }}

  package:
    runs-on: ubuntu-20.04
    needs: [clippy, build]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: target/out
      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: tip
          title: Development build
          prerelease: true
          files: target/out/*/*
